name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true


[observability]
enabled = true


[[d1_databases]]
binding = "db"
database_name = "mail_db"
database_id = "c5b1285c-8484-4b0b-a36e-58f62863ef1f"


[[kv_namespaces]]
binding = "kv"
id = "6fc4701e235a49aba1fa70fe901ff3a9"


#[[r2_buckets]]
#binding = "r2"
#bucket_name = ""


#[[send_email]]
#name = "email"


[ai]
binding = "ai"


[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true


[triggers]
crons = ["0 16 * * *"]


[vars]
domain = ["haoyangmaoedu.dpdns.org"]
admin = "admin@haoyangmaoedu.dpdns.org"
jwt_secret = "9sK7dP2vR5zQ8bN3xG1jT6mC0aF4hL9wY2uE7rB5kD8sJ0nX3qZ6gV1cM4tH7lW2yU5eR8bK0dS3jN6xG1pT9mC4fH7lW2yU5eR8bK0dS3jN6xG1pT9mC4f"


[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
